### ISSUE TITLE
Develop Branch

### ISSUE THREAD

**Issue by timmaybrown** [abramadams/dao#14]
Looks like you've made some adjustments to the develop branch. Would it be ok to clone that branch to get those fixes? Any reason they weren't merged to master?

This seems like a very cool project and was going to try to pop it into my Coldbox application. Any reason not to? I saw your disclaimer, but it seems like for using the basic DAO stuff this will be very useful to allow me to write complex queries in script without all the oddities of ACF script queries.

Thanks!

**Comment by abramadams** [comment]
The develop branch has some significant changes to the BaseModelObject (renamed Norm) side of this library (ORM, oData, etc...).  The DAO portion (read(), update(), insert() delete(), etc...) remains much the same, so if you are using it for DAO stuff then you should be good with develop.

The reason I haven't merged into master yet is that I'm not 100% satisfied with the dynamic Norm relationships.  There are known issues with loading entities with several related child entities in that it is a very expensive operation and needs to be refined.  I just haven't had the time to do anything with it yet.

I'm building out a fairly large angular app that communicates to my back-end via the oData protocol (which relies on Norm's functionality) so I expect to be addressing this in the next couple months; at which point I'll merge back into master.

**Comment by abramadams** [comment]
Merged Develop into Master! If you are still using the 0.1.x version you can still grab that at on the master-0.1.x branch.
