### ISSUE TITLE
Lucee & linq.run()

### ISSUE THREAD

**Issue by ivanionut** [abramadams/dao#28]
hi @abramadams ,

`linq.run()` returns absolutely nothing.

I debugged on `dao.read()` and inserted a dump before the return (`dump(LOCAL[arguments.name])`) and it returns the query result correctly.

it seems like a problem when the call to the `linq.run()` function.
Could it be a problem with Lucee 5.3.8.206 version?

thanks,
Ivan

**Comment by abramadams** [comment]
Hi @ivanionut, was your code working before on earlier versions of Lucee?  How is `linq` defined?  If you're dumping the query results called from linq.cfm:run > dao.read and getting query results, I'm not sure why that wouldn't return.  Maybe a little more context from your code will help me understand the issue.

**Comment by ivanionut** [comment]
hi @abramadams

> was your code working before on earlier versions of Lucee?

today is the first day I use your `dao.cfc` component

> How is linq defined? 

```js
var dao = new com.dao.database.dao( dsn = request.dsn, dbtype = "mssql" );
var query = dao.from( "users" ).run();

dump( query ); // empty ??

```

if I do this (without `run()`), I can see the methods of the component.

```js
var query = dao.from( "users" );
dump( query );

```


if I put a `dump()` in `dao.cfc:read()`, the dump returns the query correctly:

```js
	public any function read(
			 string sql = "",
			 struct params = {},
			 string name = "ret_#listFirst(createUUID(),'-')#_#getTickCount()#",
			 struct QoQ = {},
			 any cachedwithin = "",
			 string table = "",
			 string alias = "",
			 string columns = "",
			 string where = "",
			 any limit = "",
			 any offset = "",
			 string orderby = "",
			 string returnType = "query",
			 boolean returnEmptyStruct = false,
			 string file = "",
			 any map = "",
			 boolean forceLowercaseKeys = false
	){


			// etc...


				dump( var = LOCAL[ arguments.name ], abort = true ); // <--- here
				
				return LOCAL[ arguments.name ];
			}
		}
	}

**Comment by abramadams** [comment]
Strange.  The linq.cfm:run() method simply delegates to dao.read().  I would expect it to pass through.  I've tested this locally on Lucee 5.3.8 against MSSQL 2019 and I get the query results.  In testing I finally got around to bringing the MSSQL tests up to date and in the process found a few issues that I don't think would have impacted you, but worth installing the latest (1.0.3) and trying again.

**Comment by abramadams** [comment]
I was surprised that the changes I made would have had any impact on what you're seeing.  Are there any errors being logged?  What version of SQL? Can you share the table definition?

**Comment by abramadams** [comment]
Hi @ivanionut, I just wanted to follow-up and see if you were able to get this working.  I've not been able to reproduce in my testing, but perhaps there's some db/driver version or some other combination of things causing the issue for you.  If all is good I'll close this issue.

**Comment by ivanionut** [comment]
hi @abramadams and sorry for the delay
I didn't do any further tests. Today I tried again and it _"magically_" works. I don't understand... For the moment close the ticket. Thanks for your patience!
